# Generated by Django 6.0.1 on 2026-02-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='publishedDate',
            field=models.DateField(null=True),
        ),
    ]
