# Generated by Django 6.0.1 on 2026-02-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_library_publisheddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=100)),
                ('eventDate', models.DateField()),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'event',
            },
        ),
    ]
